# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-27 12:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(blank=True, max_length=500, null=True)),
                ('account_type', models.IntegerField(blank=True, choices=[(0, 'student'), (1, 'staff'), (3, 'department'), (4, 'guest')], null=True)),
                ('dob', models.DateField(blank=True, null=True)),
                ('first_name', models.CharField(blank=True, max_length=500, null=True)),
                ('last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('pin', models.IntegerField(blank=True, null=True)),
                ('email', models.EmailField(max_length=100)),
                ('blood_group', models.CharField(max_length=10)),
                ('religion', models.CharField(max_length=100)),
                ('profile_pic_url', models.CharField(blank=True, max_length=5000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='academics.User')),
            ],
            bases=('academics.user',),
        ),
        migrations.CreateModel(
            name='school',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='academics.User')),
                ('type', models.IntegerField(choices=[(0, 'Matriculation'), (1, 'State Board'), (2, 'CBSE'), (3, 'ICSE'), (4, 'Other')], default=4)),
                ('id_number', models.CharField(blank=True, max_length=1000, null=True)),
            ],
            bases=('academics.user',),
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='academics.User')),
                ('roll_no', models.CharField(blank=True, max_length=1000, null=True)),
                ('admission_no', models.CharField(blank=True, max_length=1000, null=True)),
            ],
            bases=('academics.user',),
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='academics.User')),
                ('teacher_id', models.CharField(blank=True, max_length=100, null=True)),
                ('specialization', models.TextField()),
                ('resume_url', models.CharField(blank=True, max_length=5000, null=True)),
            ],
            bases=('academics.user',),
        ),
    ]
